const WORDS = [
  // ── REAL ──────────────────────────────────────────────
  { word: "PETRICHOR",       real: true,  def: "The pleasant smell of rain on dry earth." },
  { word: "DEFENESTRATE",    real: true,  def: "To throw someone out of a window." },
  { word: "CALLIPYGIAN",     real: true,  def: "Having well-shaped buttocks." },
  { word: "SNOLLYGOSTER",    real: true,  def: "A shrewd, unprincipled person, especially a politician." },
  { word: "LIMERENCE",       real: true,  def: "An involuntary obsessive state of longing for another person." },
  { word: "PANDICULATION",   real: true,  def: "The act of stretching and yawning at the same time." },
  { word: "BORBORYGMUS",     real: true,  def: "A rumbling noise made by gas moving through the intestines." },
  { word: "SUSURRUS",        real: true,  def: "A whispering or rustling sound." },
  { word: "FLIBBERTIGIBBET", real: true,  def: "A frivolous, excessively talkative person." },
  { word: "COLLYWOBBLES",    real: true,  def: "Intense anxiety or a stomach upset." },
  { word: "KERFUFFLE",       real: true,  def: "A commotion or fuss caused by a conflict." },
  { word: "LOLLYGAG",        real: true,  def: "To spend time aimlessly." },
  { word: "WIDDERSHINS",     real: true,  def: "In a direction contrary to the sun's course — counterclockwise." },
  { word: "CATTYWAMPUS",     real: true,  def: "Askew, awry, or in disarray." },
  { word: "DISCOMBOBULATE",  real: true,  def: "To confuse or disconcert someone." },
  { word: "TARADIDDLE",      real: true,  def: "A petty lie or pretentious nonsense." },
  { word: "WAMBLE",          real: true,  def: "To feel nauseous; to move unsteadily." },
  { word: "ZUGZWANG",        real: true,  def: "A situation where any move you make will damage your position." },
  { word: "APRICITY",        real: true,  def: "The warmth of the sun in winter." },
  { word: "VELLEITY",        real: true,  def: "A wish too faint to lead to action." },
  { word: "MUMPSIMUS",       real: true,  def: "Stubbornly sticking to a custom known to be wrong." },
  { word: "SCRIPTURIENT",    real: true,  def: "Having a violent urge to write." },
  { word: "SLUBBERDEGULLION",real: true,  def: "A slovenly, worthless person." },
  { word: "GROKE",           real: true,  def: "To stare at someone eating, hoping they'll give you food." },
  { word: "QUODLIBET",       real: true,  def: "A philosophical point proposed for debate; a musical medley." },
  { word: "MELLIFLUOUS",     real: true,  def: "Pleasingly smooth and musical to hear." },
  { word: "QUIXOTIC",        real: true,  def: "Extremely idealistic and unrealistic." },
  { word: "OBSTREPEROUS",    real: true,  def: "Noisy and difficult to control." },
  { word: "LOQUACIOUS",      real: true,  def: "Tending to talk a great deal." },
  { word: "PERSPICACIOUS",   real: true,  def: "Having a keen, accurate insight into things." },
  { word: "RECALCITRANT",    real: true,  def: "Stubbornly resistant to authority." },
  { word: "HOBBLEDEHOY",     real: true,  def: "An awkward, clumsy young person." },
  { word: "LAGNIAPPE",       real: true,  def: "A small gift given to a customer alongside a purchase." },
  { word: "MALARKEY",        real: true,  def: "Meaningless talk; nonsense." },
  { word: "SCALAWAG",        real: true,  def: "A mischievous but amusing rascal." },
  { word: "TMESIS",          real: true,  def: "Inserting a word into the middle of another word (e.g. 'abso-blooming-lutely')." },
  { word: "APOPHENIA",       real: true,  def: "Seeing connections between unrelated things." },
  { word: "NOCTILUCA",       real: true,  def: "A luminescent marine organism that makes the sea glow at night." },
  { word: "ULTRACREPIDARIAN",real: true,  def: "Giving opinions beyond one's area of knowledge." },
  { word: "SONDER",          real: true,  def: "The realization that each passerby has a life as vivid as your own." },
  { word: "HIRAETH",         real: true,  def: "A deep longing for a home you can't return to." },
  { word: "FERNWEH",         real: true,  def: "An ache for distant places; the opposite of homesickness." },
  { word: "SCHADENFREUDE",   real: true,  def: "Pleasure from another person's misfortune." },
  { word: "KUMMERSPECK",     real: true,  def: "Weight gained from emotional overeating (literally 'grief bacon')." },
  { word: "FORELSKET",       real: true,  def: "The euphoria of falling in love for the first time." },
  { word: "SERENDIPITY",     real: true,  def: "A happy accident; finding something good while looking for something else." },
  { word: "EPHEMERAL",       real: true,  def: "Lasting for a very short time." },
  { word: "BIBLIOPHILE",     real: true,  def: "A person who loves and collects books." },
  { word: "PALIMPSEST",      real: true,  def: "A manuscript where old writing has been erased and written over, with traces remaining." },
  { word: "PHOSPHENE",       real: true,  def: "The light you see when you press on your closed eyelids." },
  { word: "CRUCIVERBALIST",  real: true,  def: "A person who designs or is very enthusiastic about crossword puzzles." },
  { word: "TINTINNABULATION",real: true,  def: "A ringing or tinkling sound, like a bell." },
  { word: "PSITHURISM",      real: true,  def: "The sound of wind through trees." },
  { word: "VELLICHOR",       real: true,  def: "The strange wistfulness of used bookshops." },
  { word: "MAMIHLAPINATAPAI",real: true,  def: "A look shared by two people each wishing the other would initiate something." },
  { word: "LOGORRHEA",       real: true,  def: "Excessive and often incoherent talkativeness." },
  { word: "CREPUSCULAR",     real: true,  def: "Relating to twilight; active at dawn or dusk." },
  { word: "PALIMONY",        real: true,  def: "Compensation claimed by one partner after the break-up of an unmarried couple." },
  { word: "OMPHALOSKEPSIS",  real: true,  def: "Contemplating one's navel as an aid to meditation." },
  { word: "SIALOQUENT",      real: true,  def: "Prone to spraying spit while talking." },
  { word: "GARDEROBE",       real: true,  def: "A wardrobe; also a medieval toilet built into a castle wall." },
  { word: "SNUDGE",          real: true,  def: "To be thrifty to the point of miserliness." },
  { word: "WUTHER",          real: true,  def: "To move with a sullen roar (of wind)." },
  { word: "GROAK",           real: true,  def: "To silently watch someone eating, hoping to be offered some." },
  { word: "BLATHERSKITE",    real: true,  def: "A person who talks at great length without making sense." },
  { word: "FOOFARAW",        real: true,  def: "A great fuss about something trivial; excessive ornamentation." },
  { word: "GARDYLOO",        real: true,  def: "A historical warning cry before throwing slops from a window." },
  { word: "NINCOMPOOP",      real: true,  def: "A foolish or stupid person." },
  { word: "POPINJAY",        real: true,  def: "A vain, conceited person who talks too much." },
  { word: "BUMFUZZLE",       real: true,  def: "To confuse or fluster someone." },
  { word: "SNIGGLE",         real: true,  def: "To fish for eels by poking a baited hook into their hiding place." },
  { word: "RAWMAISH",        real: true,  def: "Nonsensical talk; gibberish." },
  { word: "GONGOOZLE",       real: true,  def: "To stare at boats on a canal for entertainment." },
  { word: "MUGWUMP",         real: true,  def: "A person who remains aloof from political party divisions." },
  { word: "CWTCH",           real: true,  def: "A Welsh word for a small storage space; also a loving cuddle." },
  { word: "SHEMOZZLE",       real: true,  def: "A state of chaos or confusion." },
  { word: "ABSQUATULATE",    real: true,  def: "To leave somewhere abruptly." },

  // ── REAL: body parts with names nobody knows ──────────
  { word: "AGLET",           real: true,  def: "The plastic or metal tip at the end of a shoelace." },
  { word: "TITTLE",          real: true,  def: "The small dot placed over the letters i and j." },
  { word: "PHILTRUM",        real: true,  def: "The vertical groove between your nose and upper lip." },
  { word: "GLABELLA",        real: true,  def: "The smooth flat area of skin between your eyebrows." },
  { word: "PURLICUE",        real: true,  def: "The space between the thumb and forefinger when the hand is spread." },
  { word: "LUNULA",          real: true,  def: "The white crescent-shaped area at the base of a fingernail." },
  { word: "TRAGUS",          real: true,  def: "The small pointed flap of cartilage in front of the ear canal." },
  { word: "HALLUX",          real: true,  def: "The big toe." },
  { word: "CANTHUS",         real: true,  def: "The inner or outer corner of the eye." },
  { word: "RASCETA",         real: true,  def: "The creases on the inside of your wrist." },

  // ── REAL: funny-sounding but genuine ──────────────────
  { word: "FLUMMOX",         real: true,  def: "To perplex or bewilder someone completely." },
  { word: "HORNSWOGGLE",     real: true,  def: "To cheat or deceive someone." },
  { word: "BAMBOOZLE",       real: true,  def: "To fool or deceive someone." },
  { word: "CODSWALLOP",      real: true,  def: "Nonsense; rubbish." },
  { word: "BALDERDASH",      real: true,  def: "Senseless talk; utter nonsense." },
  { word: "SKEDADDLE",       real: true,  def: "To leave a place hurriedly." },
  { word: "RAPSCALLION",     real: true,  def: "A mischievous person; a rascal." },
  { word: "CURMUDGEON",      real: true,  def: "A bad-tempered, uncooperative old person." },
  { word: "LOLLOP",          real: true,  def: "To move in a loose, ungainly way." },
  { word: "NINNYHAMMER",     real: true,  def: "A fool or simpleton." },
  { word: "WHIPPERSNAPPER",  real: true,  def: "A young person who is presumptuous or overconfident." },
  { word: "MILQUETOAST",     real: true,  def: "A timid, unassertive, easily dominated person." },
  { word: "RIGMAROLE",       real: true,  def: "A long, complicated, and seemingly pointless procedure." },
  { word: "SKULDUGGERY",     real: true,  def: "Underhand or unscrupulous behavior." },
  { word: "SHENANIGAN",      real: true,  def: "A secret or dishonest activity; mischief." },
  { word: "FLIMFLAM",        real: true,  def: "Nonsense; also, a confidence trick." },
  { word: "BUMPTIOUS",       real: true,  def: "Irritatingly self-assertive." },
  { word: "SOCKDOLAGER",     real: true,  def: "Something extraordinary; a decisive blow or argument." },
  { word: "CALLITHUMP",      real: true,  def: "A noisy, boisterous parade or celebration with makeshift instruments." },
  { word: "GRIFFONAGE",      real: true,  def: "Careless, illegible handwriting." },
  { word: "BROUHAHA",        real: true,  def: "A noisy and overexcited reaction to something." },
  { word: "HULLABALOO",      real: true,  def: "A commotion; a fuss." },
  { word: "TCHOTCHKE",       real: true,  def: "A small trinket or knickknack." },
  { word: "KVETCH",          real: true,  def: "To complain persistently and chronically." },
  { word: "KIBITZ",          real: true,  def: "To give unwanted advice; to chat while others work." },
  { word: "CHUTZPAH",        real: true,  def: "Shameless audacity; supreme self-confidence." },
  { word: "KLUTZ",           real: true,  def: "A clumsy person." },
  { word: "SPELUNKER",       real: true,  def: "A person who explores caves as a hobby." },
  { word: "LUTHIER",         real: true,  def: "A person who makes or repairs stringed instruments." },
  { word: "FARRIER",         real: true,  def: "A person who shoes horses; a blacksmith who specializes in hooves." },
  { word: "CORDWAINER",      real: true,  def: "A shoemaker who makes new shoes (as opposed to repairing them)." },
  { word: "FLETCHER",        real: true,  def: "A person who makes arrows." },

  // ── REAL: words from other languages ──────────────────
  { word: "MERAKI",          real: true,  def: "Greek: doing something with soul, creativity, and love put into it." },
  { word: "TOSKA",           real: true,  def: "Russian: a vague, deep longing with nothing to long for." },
  { word: "SOBREMESA",       real: true,  def: "Spanish: the time spent talking at the table after a meal." },
  { word: "WALDEINSAMKEIT",  real: true,  def: "German: the peaceful, eerie feeling of being alone in the woods." },
  { word: "FREMDSCHÄMEN",    real: true,  def: "German: feeling vicarious embarrassment for someone else." },
  { word: "VERSCHLIMMBESSERN", real: true, def: "German: making something worse in a well-intentioned attempt to improve it." },
  { word: "JAYUS",           real: true,  def: "Indonesian: a joke so unfunny it becomes funny." },
  { word: "DÉPAYSEMENT",     real: true,  def: "French: the disorienting feeling of being in a foreign country." },

  // ── REAL: literary / intellectual ─────────────────────
  { word: "TERGIVERSATE",    real: true,  def: "To make conflicting statements; to avoid a clear position." },
  { word: "RODOMONTADE",     real: true,  def: "Vainglorious boasting or bragging." },
  { word: "OLEAGINOUS",      real: true,  def: "Excessively complimentary; fawning." },
  { word: "SESQUIPEDALIAN",  real: true,  def: "Given to using long words; of or relating to a long word." },
  { word: "CIRCUMLOCUTION",  real: true,  def: "The use of many words where fewer would do." },
  { word: "PUSILLANIMOUS",   real: true,  def: "Lacking courage; timid and cowardly." },
  { word: "PERSIFLAGE",      real: true,  def: "Light and slightly contemptuous mockery or banter." },
  { word: "TRUCULENT",       real: true,  def: "Eager to argue or fight; aggressively defiant." },
  { word: "BELLICOSE",       real: true,  def: "Inclined to start quarrels or wars." },
  { word: "QUERULOUS",       real: true,  def: "Complaining in a petulant or whining manner." },
  { word: "SOPORIFIC",       real: true,  def: "Tending to induce drowsiness or sleep." },
  { word: "LUGUBRIOUS",      real: true,  def: "Looking or sounding sad and dismal." },
  { word: "LACHRYMOSE",      real: true,  def: "Tearful; given to weeping." },
  { word: "MAUDLIN",         real: true,  def: "Self-pityingly or tearfully sentimental." },
  { word: "LIMINAL",         real: true,  def: "Occupying a position at or on both sides of a threshold or boundary." },
  { word: "LACUNA",          real: true,  def: "A gap or missing portion, especially in a manuscript or series." },
  { word: "PALAVER",         real: true,  def: "Lengthy and tedious fuss or discussion." },
  { word: "EGREGIOUS",       real: true,  def: "Outstandingly bad; shockingly wrong." },
  { word: "FATUOUS",         real: true,  def: "Silly and pointless; vacuous." },
  { word: "INEFFABLE",       real: true,  def: "Too great or extreme to be expressed in words." },
  { word: "EBULLIENT",       real: true,  def: "Cheerful and full of energy; bubbling over with enthusiasm." },
  { word: "VITUPERATIVE",    real: true,  def: "Bitter and abusive; using strong language to criticize." },
  { word: "NONPLUSSED",      real: true,  def: "Bewildered; so surprised that one is unsure how to react." },
  { word: "MAGNILOQUENT",    real: true,  def: "Using high-flown or pompous language." },

  // ── FAKE ──────────────────────────────────────────────
  { word: "FLORBID",         real: false },
  { word: "ZANTHROPE",       real: false },
  { word: "GRIBBOUS",        real: false },
  { word: "SNORTLE",         real: false },
  { word: "PLIMBLE",         real: false },
  { word: "QUOZZY",          real: false },
  { word: "DRABULOUS",       real: false },
  { word: "FRUMPLE",         real: false },
  { word: "TRAMBLE",         real: false },
  { word: "GLORPULENT",      real: false },
  { word: "WUMBLISH",        real: false },
  { word: "BLORBIFY",        real: false },
  { word: "CRUMBLESCENT",    real: false },
  { word: "FLIBBERTINE",     real: false },
  { word: "GLUMPLE",         real: false },
  { word: "FROBULATE",       real: false },
  { word: "SPROCKLE",        real: false },
  { word: "FLURBLE",         real: false },
  { word: "SNARPLE",         real: false },
  { word: "GLARPLE",         real: false },
  { word: "WHOMBLE",         real: false },
  { word: "SNAZZLE",         real: false },
  { word: "DRATLING",        real: false },
  { word: "FLAMBLE",         real: false },
  { word: "SNOOTLE",         real: false },
  { word: "GROMBLOUS",       real: false },
  { word: "WUMBLE",          real: false },
  { word: "DRAZZLE",         real: false },
  { word: "SQUIBBLE",        real: false },
  { word: "PLONKSOME",       real: false },
  { word: "FLIBSTER",        real: false },
  { word: "GROZZLE",         real: false },
  { word: "SNIMBLE",         real: false },
  { word: "FLURBISH",        real: false },
  { word: "SQUUMBLE",        real: false },
  { word: "BLORBULENT",      real: false },
  { word: "SNAZZULOUS",      real: false },
  { word: "GRUMBLATE",       real: false },
  { word: "FLOBBER",         real: false },
  { word: "WHUMBLOUS",       real: false },
  { word: "CRUMBLICATE",     real: false },
  { word: "GLORBISH",        real: false },
  { word: "TRUMBLOUS",       real: false },
  { word: "SNIMBLY",         real: false },
  { word: "FLURPISH",        real: false },
  { word: "BLATHERSKULL",    real: false },
  { word: "FRUMBLOUS",       real: false },
  { word: "SPLOINKLE",       real: false },
  { word: "WAZZIFY",         real: false },
  { word: "DROMBULATE",      real: false },
  { word: "SNORFLE",         real: false },
  { word: "GLIBBERING",      real: false },
  { word: "TRABBISH",        real: false },
  { word: "FLIBMUCK",        real: false },
  { word: "CRUMBLISH",       real: false },
  { word: "SNUBBOCK",        real: false },
  { word: "GLORPIFY",        real: false },
  { word: "WUBBERLY",        real: false },
  { word: "SNAZZWORT",       real: false },
  { word: "DROMBISH",        real: false },
  { word: "GRUMBLECRAFT",    real: false },
  { word: "FLORBULATE",      real: false },
  { word: "SNUBBERY",        real: false },
  { word: "WAZZLEMENT",      real: false },
  { word: "GRIBBLESOME",     real: false },
  { word: "TRUMBULATE",      real: false },
  { word: "SNORFULOUS",      real: false },
  { word: "BLORBLE",         real: false },
  { word: "FRUMBLICATE",     real: false },
  { word: "SNARBLOUS",       real: false },
  { word: "GLORPSOME",       real: false },

  // ── FAKE: more ────────────────────────────────────────
  { word: "FLOBULATE",       real: false },
  { word: "SNAZZLEMENT",     real: false },
  { word: "PLOMBLISH",       real: false },
  { word: "DRABULATION",     real: false },
  { word: "FLIMBLESOME",     real: false },
  { word: "GRUMBLATION",     real: false },
  { word: "SNORBLESOME",     real: false },
  { word: "BLORBULATE",      real: false },
  { word: "SNAZZLESOME",     real: false },
  { word: "GLORPISH",        real: false },
  { word: "CRUMBLATION",     real: false },
  { word: "SNORBLIFY",       real: false },
  { word: "TRUMBLESCENCE",   real: false },
  { word: "BLORBESCENT",     real: false },
  { word: "WUMBLESCENT",     real: false },
  { word: "FRUMBLATORY",     real: false },
  { word: "BLORPISH",        real: false },
  { word: "DROMBLICATE",     real: false },
  { word: "FLOBBERSOME",     real: false },
  { word: "GRUMBLESCENT",    real: false },
  { word: "SNARGLISH",       real: false },
  { word: "QUIBBLANCE",      real: false },
  { word: "SNAZZIFEROUS",    real: false },
  { word: "GRUMBLATIONAL",   real: false },
  { word: "BLORPULATION",    real: false },
  { word: "SNORBLIFICATION", real: false },
  { word: "WUMBLIFICATION",  real: false },
  { word: "SNAZZLIFICATION", real: false },
  { word: "TRUMBLIFICATION", real: false },
  { word: "BLORBIFICATION",  real: false },
  { word: "SNORBLERY",       real: false },
  { word: "FRUMBLERY",       real: false },
  { word: "WUMBLERY",        real: false },
  { word: "GLORPERY",        real: false },
  { word: "BLORPERY",        real: false },
  { word: "DRABBLESOME",     real: false },
  { word: "SNORBLESCENT",    real: false },
  { word: "FRUMBLIFICATION", real: false },
  { word: "SNAZZLORY",       real: false },
  { word: "GLORPULATE",      real: false },
  { word: "WUMBLOUS",        real: false },
  { word: "GLORPOUS",        real: false },
  { word: "SNAZZLOUS",       real: false },
  { word: "FLUMBLOUS",       real: false },
  { word: "CRUMBLOUS",       real: false },
  { word: "GLORPIFORM",      real: false },
  { word: "SNORBLIFORM",     real: false },
  { word: "WUMBLIFORM",      real: false },
  { word: "FRUMBLIFORM",     real: false },
  { word: "BLORPIFORM",      real: false },
  { word: "SNAZZLIFORM",     real: false },
  { word: "DROMBIFORM",      real: false },
  { word: "GLORPWISE",       real: false },
  { word: "SNORBLWISE",      real: false },
  { word: "FRUMBLEWISE",     real: false },
  { word: "WUMBLEWISE",      real: false },
  { word: "SNAZZLEWISE",     real: false },
  { word: "BLORPWISE",       real: false },
  { word: "TRUMBLESOME",     real: false },
  { word: "FLOBBLESOME",     real: false },
  { word: "GLORPESCENT",     real: false },
  { word: "SNORBLOUS",       real: false },
  { word: "FRUMBLESCENT",    real: false },
  { word: "BLORBLESOME",     real: false },
  { word: "WUMBLESOME",      real: false },
];

function shuffleWords() {
  const arr = [...WORDS];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}
