// Each entry: { word, difficulty: 1|2|3 }
// Adapted from unscramble/words.js (hint dropped) plus extra Y-containing words
// so every difficulty tier has enough candidates for "Y counts this round!" rounds.
const WORDS = [
  // ── Tier 1 ───────────────────────────────────────────────────────────────
  { word: 'PALM',  difficulty: 1 },
  { word: 'SWAN',  difficulty: 1 },
  { word: 'DUSK',  difficulty: 1 },
  { word: 'COVE',  difficulty: 1 },
  { word: 'GLEN',  difficulty: 1 },
  { word: 'HELM',  difficulty: 1 },
  { word: 'FERN',  difficulty: 1 },
  { word: 'MAST',  difficulty: 1 },
  { word: 'GUST',  difficulty: 1 },
  { word: 'CLAM',  difficulty: 1 },
  { word: 'SMOG',  difficulty: 1 },
  { word: 'WICK',  difficulty: 1 },
  { word: 'PERK',  difficulty: 1 },
  { word: 'HULK',  difficulty: 1 },
  { word: 'IRIS',  difficulty: 1 },
  { word: 'HAPPY', difficulty: 1 },
  { word: 'CANDY', difficulty: 1 },
  { word: 'MYTH',  difficulty: 1 },
  { word: 'GYM',   difficulty: 1 },

  // ── Tier 2 ───────────────────────────────────────────────────────────────
  { word: 'BLAZE',  difficulty: 2 },
  { word: 'CRISP',  difficulty: 2 },
  { word: 'GRAZE',  difficulty: 2 },
  { word: 'KNACK',  difficulty: 2 },
  { word: 'LUNAR',  difficulty: 2 },
  { word: 'PRANK',  difficulty: 2 },
  { word: 'QUIRK',  difficulty: 2 },
  { word: 'SLOTH',  difficulty: 2 },
  { word: 'WALTZ',  difficulty: 2 },
  { word: 'BRAWN',  difficulty: 2 },
  { word: 'FLINT',  difficulty: 2 },
  { word: 'GROAN',  difficulty: 2 },
  { word: 'DWARF',  difficulty: 2 },
  { word: 'PLUMB',  difficulty: 2 },
  { word: 'TRYST',  difficulty: 2 },
  { word: 'SYSTEM', difficulty: 2 },
  { word: 'SYRUP',  difficulty: 2 },
  { word: 'PLENTY', difficulty: 2 },

  // ── Tier 3 ───────────────────────────────────────────────────────────────
  { word: 'SPHINX',  difficulty: 3 },
  { word: 'JIGSAW',  difficulty: 3 },
  { word: 'PASTRY',  difficulty: 3 },
  { word: 'OYSTER',  difficulty: 3 },
  { word: 'MAGNET',  difficulty: 3 },
  { word: 'MARVEL',  difficulty: 3 },
  { word: 'CANOPY',  difficulty: 3 },
  { word: 'CACTUS',  difficulty: 3 },
  { word: 'TURNIP',  difficulty: 3 },
  { word: 'BISHOP',  difficulty: 3 },
  { word: 'FAMINE',  difficulty: 3 },
  { word: 'SUMMIT',  difficulty: 3 },
  { word: 'BALCONY', difficulty: 3 },
  { word: 'LANTERN', difficulty: 3 },
  { word: 'PILGRIM', difficulty: 3 },
  { word: 'RHYTHM',  difficulty: 3 },
  { word: 'CRYPT',   difficulty: 3 },
  { word: 'MYSTERY', difficulty: 3 },
];
